app/__init__.py
from flask import Flask, render_template, request
from flaskext.mysql import MySQL
from app.blueprints import home

def create_app():
    app = Flask(__name__)
    home.configure(app)

    return app

app/blueprints/home.py
from flask import Blueprint, Flask, render_template, request
from flaskext.mysql import MySQL
from app.database import Database
import requests
import json

db = Database()
bp_app = Blueprint("home", __name__)

def configure(app):
   app.register_blueprint(bp_app)

@bp_app.route("/")
def index():
   return render_index()

@bp_app.route("/edit", methods=['POST','GET'])
def edit():
   if request.method == 'POST':
      send_game(request)
      return render_index()
   else:
      game_id = request.args.get('game_id')
      game = db.find_game_by_id(game_id)
      return render_template('edit.html', game = game)
   
   
@bp_app.route("/create", methods=['POST','GET'])
def create():
   if request.method == 'GET' :
      return render_template('create.html')
   else:
      send_game(request)
      return render_index()

def render_index():
   games = db.events_list()
   return render_template('index.html', games = games)

def send_game(request):
   send_dict = {} 
   games = []
   games.append(create_game(request))
   send_dict["data"] = games
   send_dict["email"] = request.form['email']
   game_json = json.dumps(send_dict)
   url = 'http://desafio.logus.tech/desafio'
   requests.post(url, data = game_json)

def create_game(request):
   game_dict = {}
   game_dict["id"] = request.form['game_id'] 
   game_dict["teams"] = request.form['teams']
   game_dict["home"] = request.form['home']
   game_dict["away"] = request.form['away']
   game_dict["date"] = request.form['date']
   return game_dict

app/templates/create.html
<!DOCTYPE html>
<html>
	<head>
		<title>Logus Tech - Novo Jogo</title>
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
	</head>
	<body>
		<div class="container">
			<form method="POST" action="/create">
				<input type="hidden" name="game_id" value="0" />
				<div class="text-center mb-4">
					<h1 class="h3 mb-3 font-weight-normal" style="padding-top: 30px;">Criar Jogo</h1>
				</div>
				<div class="form-label-group">
					<label for="inputEmail">Times</label>
					<input type="text" name="teams"  id="inputEmail" class="form-control" placeholder="Times" required="" autofocus="">
				</div>
				<div class="form-label-group">
					<label for="inputPassword">Casa cotação</label>
					<input type="number" name="home" step="0.01" id="inputPassword" class="form-control" placeholder="Casa cotação" required="">
				</div>
				<div class="form-label-group">
					<label for="inputPassword">Visitantes cotação</label>
					<input type="number" name="away" step="0.01" id="inputPassword" class="form-control" placeholder="Visitantes cotação" required="">
				</div>
				<div class="form-label-group">
					<label for="inputPassword">Dia</label>
					<input type="text" name="date" id="inputPassword" class="form-control" placeholder="Dia" required="">
				</div>
				<div class="form-label-group">
					<label for="inputEmail">Email</label>
					<input type="email" name="email" id="inputEmail" class="form-control" placeholder="Email" required="" autofocus="">
				</div>
				<div class="form-label-group">
					<button class="btn btn-lg btn-primary btn-block" type="submit">Salvar</button>
				</div>
			</form>
		</div>
		<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
	</body>
</html>

app/templates/edit.html
<!DOCTYPE html>
<html>
	<head>
		<title>Logus Tech - Edit</title>
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
	</head>
	<body>
		<div class="container">
			<form method="POST" action="/edit">
				<input type="hidden" name="game_id" value="{{game.id}}" />
				<div class="text-center mb-4">
					<h1 class="h3 mb-3 font-weight-normal" style="padding-top: 30px;">Editar Jogo</h1>
				</div>
				<div class="form-label-group">
					<label for="inputEmail">Times</label>
					<input type="text" name="teams" value="{{game.teams}}" id="inputEmail" class="form-control" placeholder="Times" required="" autofocus="">
				</div>
				<div class="form-label-group">
					<label for="inputPassword">Casa cotação</label>
					<input type="number" name="home"  value="{{game.home}}" step="0.01" id="inputPassword" class="form-control" placeholder="Casa cotação" required="">
				</div>
				<div class="form-label-group">
					<label for="inputPassword">Visitantes cotação</label>
					<input type="number" name="away"  value="{{game.away}}" step="0.01" id="inputPassword" class="form-control" placeholder="Visitantes cotação" required="">
				</div>
				<div class="form-label-group">
					<label for="inputPassword">Dia</label>
					<input type="text" name="date" value="{{game.date}}"id="inputPassword" class="form-control" placeholder="Dia" required="">
				</div>
				<div class="form-label-group">
					<label for="inputEmail">Email</label>
					<input type="email" name="email" id="inputEmail" class="form-control" placeholder="Email" required="" autofocus="">
				</div>
				<div class="form-label-group">
					<button class="btn btn-lg btn-primary btn-block" type="submit">Salvar</button>
				</div>
			</form>
		</div>
		<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
	</body>
</html>

app/templates/index.html
<!DOCTYPE html>
<html>
    <head>
        <title>Logus Tech</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
            <div class="container">
                <a class="navbar-brand" href="#">Logus Tech</a>
            </div>
        </nav>
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <h1 class="my-4" style="padding-top: 35px;"></h1>
                    <div class="card mb-4">
                    <table class="table">
                        <thead class="thead-dark">
                            <tr>
                                <th class="text-center">Times</th>
                                <th class="text-center">Casa cotação</th>
                                <th class="text-center">Visitantes cotação</th>
                                <th class="text-center">Dia</th>
                                <th class="text-center"></th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for game in games %}
                                <tr>
                                    <th scope="row">{{ game.teams }}</th>
                                    <td class="{{ 'table-success' if game.away > game.home else 'table-danger' }} text-center"> {{game.away }} </td>
                                    <td class="{{ 'table-success' if game.home > game.away else 'table-danger' }} text-center"> {{game.home }} </td>
                                    <td class="text-center"> {{game.date}} </td>
                                    <td> 
                                        <form action="{{ url_for('home.edit') }}" method="GET">
                                            <input type="hidden" name="game_id" value="{{game.id}}">
                                            <button type="submit"> Editar </button>
                                        </form>    
                                    </td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                    <div class="card-footer text-muted">
                        Posted by Yann Thor
                    </div>
                </div>
                <form action="{{ url_for('home.create') }}" method="GET">
                    <button type="submit"> Novo Jogo </button>
                </form>    
            </div>
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    </body>
</html>